### ISSUE TITLE
Navigator object more unique after

### ISSUE THREAD

**Issue by azukaar** [maximbaz/browser-fingerprint-protector#8]
When using the extension on FF, the browser's navigator object is more unique after installing than before:

Before
![image](https://user-images.githubusercontent.com/7872597/175022932-dcee814d-8a00-4e8f-969f-a75f6316a885.png)

After
![image](https://user-images.githubusercontent.com/7872597/175022961-2255863b-adc2-4133-921e-b84a6c07a940.png)

**Comment by azukaar** [comment]
Found the issue: 
On Firefox, the AppVersion is not of the form 
`"5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36"`
Like Chrome, but instead only has
`5.0 (Windows)`

So using this extension causes the browser to pretty much be unique (with other people using it)

**Comment by max-baz** [comment]
Thank you for reporting, and wow that's a good catch!
By the way, can you tell me the website you used, where the screenshots are from?

**Comment by azukaar** [comment]
https://amiunique.org

**Comment by max-baz** [comment]
Thanks once more for opening this issue! This project will no longer be maintained, as I don't believe that this battle can be won. To try to protect against fingerprinting attacks, I recommend to try using Tor Browser or similar projects.
